server:
  port: 8094


logging:
  level:
    root: INFO
  config: classpath:logback.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


spring:
  application:
    name: gy-resource
  datasource:
    url: jdbc:mysql://40.73.65.243:3306/gy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://127.0.0.1:3306/gy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 2wsgsda%lptP!3sd5rti
#    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 8
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

  redis:
    database: 1
    host: 40.73.65.243
    port: 6379
    password: adminjic123456
    jedis:
      pool:
        max-active: 20
        max-wait: 10
        max-idle: 0
        min-idle: 0
    timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:conf/mybatis-config.xml

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000